name: mobile_applications
description: A great application to share and create lists with your friends

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tuple: '^2.0.0'

  # used to choose the number of people of a list
  numberpicker: ^2.1.1

  cupertino_icons: ^1.0.0
  shared_preferences: '>2.0.0'
  settings_ui: ^1.0.0
  permission_handler: ^8.1.1
  app_settings: ^4.1.0

  # for changing the theme
  provider: ^5.0.0

  # needed to show Toast popups
  fluttertoast: ^8.0.7

  # Firebase stuff
  firebase_core: "^1.1.1"
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.2.0
  firebase_analytics: ^8.0.2
  firebase_messaging: ^10.0.2
  cloud_functions: ^2.0.0

  flutter_app_badger: ^1.2.0

  
  overlay_support: ^1.2.1

  # Login stuff
  # Let's use the most recent version from github, since there are features that we need
  flutter_login:
    git:
      url: https://github.com/malta895/flutter_login
      ref: bf400eb8463baec909c3290a01605010fc88eb63
  email_validator: ^2.0.1
  google_sign_in: ^5.0.3
  flutter_facebook_auth: ^3.4.0
 
  font_awesome_flutter: ^9.0.0


  json_annotation: ^4.0.1
  firebase_storage: ^9.0.0
  flutter_signin_button: ^2.0.0
  equatable: ^2.0.3
  intl: ^0.17.0
  animations: ^2.0.0
  image_picker: ^0.8.1+3
  expandable: ^5.0.1


  
dev_dependencies:
  json_serializable: ^4.1.3
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test: any

  # Needed to rename Android buildId, see https://pub.dev/packages/rename
  # rename: "1.2.0"

    # For information on the generic Dart part of this file, see the
    # following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

    # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
